# Generated by Django 5.1.7 on 2025-03-09 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='date_consumed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consume',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
